### ISSUE TITLE
GitLab Repository Integration: Plugin Not Adding committer details to UI

### ISSUE THREAD

**Issue by anibmurthy** [ojacques/mkdocs-git-committers-plugin-2#28]
I want to express my appreciation for creating this fantastic plugin!

I'm assuming that this plugin can also be utilized for GitLab repositories.

I made an attempt to apply this plugin to my GitLab repository, but unfortunately, I haven't observed any changes. I noticed that the `.cache/plugins/git-committers` file is generated with an empty `authors` list. I suspect that this might be the reason why no content is being added to the user interface. Below is the plugin configuration specified in `mkdocs.yaml`:

```
plugins:
  - git-committers:
      repository: anibmurthy/mkdocs
      enterprise_hostname: gitlab.com
      branch: main
```
