### ISSUE TITLE
Unable to exclude folders

### ISSUE THREAD

**Issue by nvuillam** [ojacques/mkdocs-git-committers-plugin-2#37]
Hi, I want to exclude all files located under directory docs/hardis but the following configuration does not work

How can I correct ? 

```yaml
plugins:
  - glightbox
  - search
  - git-committers:
      repository: hardisgroupcom/sfdx-hardis
      branch: main
      exclude:
      - docs/hardis/*
  ```

Thanks :)

![image](https://github.com/ojacques/mkdocs-git-committers-plugin-2/assets/17500430/85453756-6820-4b97-8c19-29426874f589)

**Comment by ojacques** [comment]
Bonjour Nicolas. Is this with 1.2.0 version (if you could check). Thanks.

**Comment by ojacques** [comment]
@nvuillam - I checked your case, and for it to work as you expect:

- Make sure that the list of folders to exclude is relative to `docs/` folder
- For subdirectories to be excluded, use [glob](https://docs.python.org/3/library/glob.html)

This config should work for you:

```
plugins:
  - glightbox
  - search
  - git-committers:
      repository: hardisgroupcom/sfdx-hardis
      branch: main
      exclude:
      - hardis/**
```

I will clarify the doc.
