### ISSUE TITLE
How should we use Github token for Github Actions workflow ?

### ISSUE THREAD

**Issue by mathisgauthey** [ojacques/mkdocs-git-committers-plugin-2#51]
Hey there !

I looked at #22, #42 and #46. But I couldn't decide what should be the standard way of creating a token for github actions.

So here's what I did : 
- I created a secret nammed `MKDOCS_GIT_COMMITTERS_APIKEY` on my epo. It holds my access token.
- I changed my plugin settings : 
```
  - git-committers:
      repository: mathisgauthey/mathisgauthey.github.io
      branch: main
      enabled: !ENV [CI, false]
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
```
- I changed my ci.yml workflow to add the token : 
```
name: ci
on:
    push:
        branches:
            - master
            - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Configure Git Credentials
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.x
            - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
            - uses: actions/cache@v3
              with:
                  key: mkdocs-material-${{ env.cache_id }}
                  path: .cache
                  restore-keys: |
                      mkdocs-material-
            - run: pip install mkdocs-material
            - run: pip install mkdocs-awesome-pages-plugin
            - run: pip install mkdocs-git-revision-date-localized-plugin
            - run: pip install mkdocs-git-committers-plugin-2
            - run: pip install "mkdocs-material[imaging]"
            - run: pip install mkdocs-callouts
            - run: |
                  export MKDOCS_GIT_COMMITTERS_APIKEY=${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}
                  mkdocs gh-deploy --force
```

I'm using an `export` and I did not see it anywhere else. Is there a better way to achieve this ? 

Thanks in advance, it works but I want to learn about why should I use this technique or another one.
