### ISSUE TITLE
Authors does not show in GitLab self-host

### ISSUE THREAD

**Issue by mahdisn76** [ojacques/mkdocs-git-committers-plugin-2#55]
I am using GitLab self-hosted and set the mkdocs configs based on the documents.
```
plugins:
  - git-committers:
      token: '...'
      gitlab_hostname: 'git.example.com'
      api_version: 'v4'
      gitlab_repository: 619
      branch: 'main'
```
What I see is that the commit details including avatar and other things are fetching correctly. 

But event though I am using material theme, it does not show any thing at the bottom of the document pages.

Any help?
