### ISSUE TITLE
GitHub Enterprise disaplays no avatars

### ISSUE THREAD

**Issue by mihaigalos** [ojacques/mkdocs-git-committers-plugin-2#58]
Using GH Enterprise, my user's avatar's URL is correctly fetched from the repo's commit, containing something like:

```
https://avatars.company.com/u/8554\?\&size\=72
```

This is ok, since an auth_header is used. But when dynamically resolving the src for the image, no auth is used and the avatar is not displayed, since the URL is  not authorized:

<img width="359" alt="Screenshot 2024-06-15 at 16 14 04" src="https://github.com/ojacques/mkdocs-git-committers-plugin-2/assets/16443090/460eaec4-a00f-41ba-a9e5-d87584cc7351">

I think this is a missing feature for auth, or the plugin may need to potentially download the avatar as an asset in the .cache folder and serve it from there.

I'm using this config:
```yaml
plugins:
  - git-committers:
      enterprise_hostname: company.com
      repository: orga/repo
      api_version: v3
      branch: main
```
