### ISSUE TITLE
cannot access gitlab repo

### ISSUE THREAD

**Issue by yuclin** [ojacques/mkdocs-git-committers-plugin-2#84]
I want to use self-hosted gitlab for this git-committers plugin.

Here are the code I wrote at mkdoc.yml

```
plugins:
  - git-committers:
      gitlab_hostname: gitlab.example.com
      gitlab_repository: 123456
      branch: main
      token: 'token'
      api_version: v4
```

But it showed "git.exc.InvalidGitRepositoryError"
Is there anything I configured uncorrectly?
